### ISSUE TITLE
Ability to include version in the .AppImage filename

### ISSUE THREAD

**Issue by dino-** [dino-/hsinstall#20]

**Comment by dino-** [comment]
linuxdeploy-plugin-appimage now names the resulting AppImage files with a hex "hash" between the appname and the architecture (like this: `foobar-f1eeeef-x86_64.AppImage`). We need to include the ability to guide the file naming pattern from hsinstall by setting an `OUTPUT` environment variable. This would work into this issue about adding a version number nicely, and is a cleaner way than hacking the file after it's written.

See [linuxdeploy-plugin-appimage docs](https://github.com/linuxdeploy/linuxdeploy-plugin-appimage).

**Comment by probonopd** [comment]
`export VERSION=... ` prior to invoking `linuxdeploy`.

**Comment by dino-** [comment]
@probonopd Ah, hidden env variable ;)  Definitely better than using `OUTPUT` Thank you.

Also, I see now the hex hash used by default seems to be the short Git commit hash.

**Comment by probonopd** [comment]
Yes, it is.
