### ISSUE TITLE
Support projects that build with cabal instead of stack

### ISSUE THREAD

**Issue by dino-** [dino-/hsinstall#41]
We should be able to detect this by the absence of a `stack.yaml` file, if I understand how this works correctly.

**Comment by dpwiz** [comment]
Risky, without `cabal.project` being present.

**Comment by dpwiz** [comment]
And sometimes there could be both, together with some nix configs if a developer is extra resourceful.

**Comment by dino-** [comment]
Risky how? I don't use cabal alone much since moving to stack years ago but I thought lately it does the nix-style local builds even without a cabal.project. But I don't really know and will get reading and experimenting.

As for nix, I wonder if people using nix would likely not need this hsinstall deployment-tree tool to begin with, relying on nix to do such things. Not really sure how people use nix.

**Comment by dpwiz** [comment]
"Risky" as in "attempts to build with some crazy package set, putting garbage everywhere".
